services:
  toyou-backend:
    image: vastsea/toyou-backend
    container_name: toyou-backend
    hostname: toyou-backend
    restart: unless-stopped
    ports:
      - "20005:20005"
    volumes:
      - ./config.toml:/usr/app/config.toml
      - ./logs:/usr/app/logs
      - ./files:/usr/app/files
      - ./profile:/usr/app/profile
      - ./trash:/usr/app/trash
    tty: true