version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: Jenkins
    hostname: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_configuration/:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    image: jenkins/ssh-agent:jdk11
    container_name: Agent
    hostname: agent
    restart: unless-stopped
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY= ${SSH_PUBKEY}