networks:
  klpbbs-survey:
    name: klpbbs-survey
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

services:
  frontend:
    image: nginx
    container_name: klpbbs-survey-frontend
    hostname: klpbbs-survey-frontend
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/etc/nginx/html
      - ./logs:/etc/nginx/logs
    ports:
      - 25000:80
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.2
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    privileged: true
  
  backend:
    image: vastsea/klpbbs-survey-backend
    container_name: klpbbs-survey-backend
    hostname: klpbbs-survey-backend
    restart: unless-stopped
    volumes:
      - ./config:/usr/app/config
      - ./logs:/usr/app/logs
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.3
    tty: true

  postgresql:
    image: postgres:14
    container_name: klpbbs_postgres
    restart: unless-stopped    
    environment: 
      POSTGRES_USER: klpbbs_survey_db
      POSTGRES_PASSWORD: ${PSQL_PWD}
      POSTGRES_DB: survey
    ports: 
      - "25001:5432"
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.4
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./postgres_service/initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: klpbbs_pgadmin
    restart: unless-stopped
    ports:
      - "25002:80"
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.5
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PSQL_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PSQL_ADMIN_PWD}
    depends_on:
      - postgresql
