networks:
  klpbbs-survey:
    name: klpbbs-survey
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

services:
  nginx:
    image: nginx
    container_name: klpbbs-survey-nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/etc/nginx/logs
    ports:
      - "40019:4002"
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.2

  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/teamvastsea/klpbbs-survey-frontend
    container_name: klpbbs-survey-frontend
    restart: unless-stopped
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.3

  backend:
    image: registry.cn-hangzhou.aliyuncs.com/teamvastsea/klpbbs-survey-backend
    container_name: klpbbs-survey-backend
    restart: unless-stopped
    volumes:
      - ./config:/usr/app/config
      - ./logs:/usr/app/logs
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.4

  postgresql:
    image: postgres:14
    container_name: klpbbs-postgres
    restart: unless-stopped    
    environment: 
      POSTGRES_USER: klpbbs_survey_db
      POSTGRES_PASSWORD: ${PSQL_PWD}
      POSTGRES_DB: survey
    ports: 
      - "40003:5432"
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.5
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./postgres_service/initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: klpbbs-pgadmin
    restart: unless-stopped
    networks:
      klpbbs-survey:
        ipv4_address: 172.25.0.6
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PSQL_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PSQL_ADMIN_PWD}
    depends_on:
      - postgresql

volumes:
  volume_pgadmin:
    name: klpbbs-vpga
