version: '3.7'

networks:
  minecraft:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

#networks:
#  default:
#    name: minecraft
#    external: true

services:
  bungeecord:
    image: vastsea/mc-zulu8-python3-env:latest
    container_name: 25565-BungeeCord
    hostname: bungeecord
    restart: unless-stopped
    ports:
      - "25565:25565"
    networks:
      minecraft:
        ipv4_address: 172.30.0.2
    volumes:
      - ../[25565]vastseaBungeecord/:/home/[25565]BungeeCord/
    entrypoint: /bin/bash
    command: -c "/home/[25565]BungeeCord/launch-bungeecord.sh"
    tty: true

  login:
    image: vastsea/mc-zulu8-python3-env:latest
    container_name: 10000-Login
    hostname: login
    restart: unless-stopped
    # ports:
    #   - 10000:10000
    networks:
      minecraft:
        ipv4_address: 172.30.0.3
    volumes:
      - ../[10000]vastseaLogin/:/home/[10000]Login/
    entrypoint: /bin/bash
    command: -c "/home/[10000]Login/launch-login.sh"
    tty: true

  build:
    image: vastsea/mc-zulu8-python3-env:latest
    container_name: 10001-Build
    hostname: build
    restart: unless-stopped
    ports:
    #   - 10001:10001
      - "24982:24982"
    networks:
      minecraft:
        ipv4_address: 172.30.0.4
    volumes:
      - ../[10001]vastseaServer/:/home/[100001]Build/
    entrypoint: /bin/bash
    command: -c "/home/[10001]Build/launch-build.sh"
    tty: true
