version: '3.7'

services:
  mongo:
    image: mongo
    container_name: MongoDB
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersafepassword
    volumes:
      - ./mongodb_data:/data/db

